### ISSUE TITLE
miFlora error on start

### ISSUE THREAD

**Issue by frippan** [zewelor/bt-mqtt-gateway#10]
When I add miflora to the config file i got an error on start

my config.yaml

    miflora:
      args:
        devices:
          herbs: C4:7C:8D:64:3B:73
        topic_prefix: miflora
      update_interval: 300

sudo ./gateway.py -d

Starting
Added: miscale with 1800 seconds interval
Traceback (most recent call last):
  File "./gateway.py", line 30, in <module>
    manager.register_workers(settings['manager']).start(mqtt)
  File "/home/pi/bt-mqtt-gateway/workers_manager.py", line 34, in register_workers
    module_obj = importlib.import_module("workers.%s" % worker_name)
  File "/usr/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 673, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/home/pi/bt-mqtt-gateway/workers/miflora.py", line 5, in <module>
    from miflora.miflora_poller import MiFloraPoller, \
ImportError: No module named 'miflora'

**Comment by bbbenji** [comment]
Please post your full config.

**Comment by frippan** [comment]
sudo pip3 install miflora did the trick. Thanks

**Comment by zewelor** [comment]
@frippan There was error in miflora worker. It should autoinstall miflora lib by itself. It should be working now without having to manually install it.
