### ISSUE TITLE
Broken pipe errors when calling getServices() 

### ISSUE THREAD

**Issue by lwestenberg** [zewelor/bt-mqtt-gateway#103]
I'm creating a new worker for Medisana scales, based on https://github.com/keptenkurk/BS440. So far everything seems pretty straight forward and similar to the ibbq. I will upload the first code asap but for now I'm having an issue when calling getServices() on a connected peripheral. I used the ibbq worker to test this, added btle.Peripheral(self.mac, **btle.ADDR_TYPE_RANDOM**) (which is required for the Medisana scale).

config entry:
ibbq:
      args:
        devices:
          badkamer: 11:22:33:44:55:66
        topic_prefix: medisanascale
      update_interval: 10

Everything works fine until I call getServices(), after that I get this error:
`Traceback (most recent call last):
  File "./gateway.py", line 67, in <module>
    manager.register_workers(global_topic_prefix).start(mqtt)
  File "/home/pi/bt-mqtt-gateway/workers_manager.py", line 88, in register_workers
    command_timeout, global_topic_prefix, **worker_config["args"]
  File "/home/pi/bt-mqtt-gateway/workers/base.py", line 7, in __init__
    self._setup()
  File "/home/pi/bt-mqtt-gateway/workers/ibbq.py", line 25, in _setup
    self.devices[name] = ibbqThermometer(mac, timeout=self.command_timeout)
  File "/home/pi/bt-mqtt-gateway/workers/ibbq.py", line 105, in __init__
    self.device = self.subscribe()
  File "/home/pi/bt-mqtt-gateway/workers/ibbq.py", line 115, in subscribe
    services = self.device.getServices()
  File "/usr/local/lib/python3.5/dist-packages/bluepy/btle.py", line 481, in getServices
    return self.services
  File "/usr/local/lib/python3.5/dist-packages/bluepy/btle.py", line 477, in services
    self._serviceMap = self.discoverServices()
  File "/usr/local/lib/python3.5/dist-packages/bluepy/btle.py", line 459, in discoverServices
    rsp = self._getResp('find')
  File "/usr/local/lib/python3.5/dist-packages/bluepy/btle.py", line 407, in _getResp
    resp = self._waitResp(wantType + ['ntfy', 'ind'], timeout)
  File "/usr/local/lib/python3.5/dist-packages/bluepy/btle.py", line 361, in _waitResp
    self._stopHelper()
  File "/usr/local/lib/python3.5/dist-packages/bluepy/btle.py", line 293, in _stopHelper
    self._helper.stdin.flush()
BrokenPipeError: [Errno 32] Broken pipe
Exception ignored in: <bound method Peripheral.__del__ of <bluepy.btle.Peripheral object at 0xb6a2e030>>
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/bluepy/btle.py", line 630, in __del__
    self.disconnect()
  File "/usr/local/lib/python3.5/dist-packages/bluepy/btle.py", line 453, in disconnect
    self._writeCmd("disc\n")
  File "/usr/local/lib/python3.5/dist-packages/bluepy/btle.py", line 305, in _writeCmd
    self._helper.stdin.flush()
BrokenPipeError: [Errno 32] Broken pipe
`

Does anybody have any idea how to fix this? It seems to me that the ibbq must have this issue as well.

**Comment by zewelor** [comment]
I would guess its either old bluez ( https://github.com/zewelor/bt-mqtt-gateway/wiki/Upgrade-Bluez-on-Raspbian ) or / and try to run as root ( I think not every bt operation is supported from user )

**Comment by westenberg** [comment]
it's not an issue with old bluez in this case. Do you maybe have an example somewhere that uses  getServices(). I think that it breaks because the next update cycle is before getServices() finishes.

What makes the Medisana scale integration a bit more challenging is that it:
connects to the ble device and should wait for a very long time (30-50 sec) to collect all handle data. After that it processes the combined output.

**Comment by Caroga** [comment]
Funny, I was trying to find a upgraded version of the BS440 python script and managed to find this repo. I'm interested in you achievements on this @westenberg. Did you managed to get this working with Medisana products?

**Comment by lwestenberg** [comment]
Yes, I had it working long time ago with Bluetooth scripts in bash but eventually didn't continue because of other priorities. The issue with by-mqtt-gateway were the timeouts. You have to wait for about 30 sec to get all the data from Medisana scales.

Perhaps I will continue with this in the future but I think it will become more of a ESP32 Bluetooth solution or Home Assistant integration than by-mqtt-gateway.
