### ISSUE TITLE
App crashes on regular basis on Raspberry PI 4

### ISSUE THREAD

**Issue by MrSpock** [zewelor/bt-mqtt-gateway#108]
Hi,
I'm trying to use app but it stops working in random time interval with following error:
```
17:10:51 Updating 3 mithermometer devices
17:11:01 Fatal error while executing worker command: RuntimeError
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/btlewrap/base.py", line 44, in __enter__
    self._backend.connect(self._mac)
  File "/usr/local/lib/python3.7/dist-packages/btlewrap/bluepy.py", line 26, in _func_wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/btlewrap/bluepy.py", line 55, in connect
    self._peripheral = Peripheral(mac, iface=iface)
  File "/usr/local/lib/python3.7/dist-packages/bluepy/btle.py", line 391, in __init__
    self._connect(deviceAddr, addrType, iface)
  File "/usr/local/lib/python3.7/dist-packages/bluepy/btle.py", line 436, in _connect
    rsp = self._getResp('stat')
  File "/usr/local/lib/python3.7/dist-packages/bluepy/btle.py", line 407, in _getResp
    resp = self._waitResp(wantType + ['ntfy', 'ind'], timeout)
  File "/usr/local/lib/python3.7/dist-packages/bluepy/btle.py", line 347, in _waitResp
    rv = self._helper.stdout.readline()
  File "/usr/local/lib/python3.7/dist-packages/interruptingcow/__init__.py", line 74, in handler
    raise exception
exceptions.DeviceTimeoutError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./gateway.py", line 91, in <module>
    raise e
  File "./gateway.py", line 73, in <module>
    mqtt.publish(_WORKERS_QUEUE.get(timeout=10).execute())
  File "/home/spock/bt-mqtt-gateway/workers_manager.py", line 52, in execute
    for message in self._callback(*self._args):
  File "/home/spock/bt-mqtt-gateway/workers/mithermometer.py", line 76, in status_update
    yield self.update_device_state(name, data["poller"])
  File "/usr/local/lib/python3.7/dist-packages/interruptingcow/__init__.py", line 153, in inner
    return func(*args, **kwargs)
  File "/home/spock/bt-mqtt-gateway/workers/mithermometer.py", line 105, in update_device_state
    payload=poller.parameter_value(attr),
  File "/usr/local/lib/python3.7/dist-packages/mithermometer/mithermometer_poller.py", line 136, in parameter_value
    self.fill_cache()
  File "/usr/local/lib/python3.7/dist-packages/mithermometer/mithermometer_poller.py", line 60, in fill_cache
    self.firmware_version()
  File "/usr/local/lib/python3.7/dist-packages/mithermometer/mithermometer_poller.py", line 109, in firmware_version
    with self._bt_interface.connect(self._mac) as connection:
  File "/usr/local/lib/python3.7/dist-packages/btlewrap/base.py", line 47, in __enter__
    self._lock.release()
RuntimeError: release unlocked lock
```

**Comment by cybe** [comment]
This is due to ChristianKuehnel/btlewrap#13. I resumed my investigation on this, because this is still a problem for me as well.

**Comment by hechi** [comment]
Hey guys,
first of all super awesome project I love it and helps a lot for my home-assistant project :) thx for the hard work.

I updated recently on my raspberry pi 3 (raspbian) and I have the same issue as @MrSpock if you need more logs or insides let me know ;)

**Comment by cybe** [comment]
@hechi This has been fixed since btlewrap version 0.0.9. #136 forces the inclusion of that version, so you might want to check if you have btlewrap in that version installed.

**Comment by zewelor** [comment]
I've bumped mithermometer version, which uses btlewrap version 0.0.9.

**Comment by cybe** [comment]
> I've bumped mithermometer version, which uses btlewrap version 0.0.9.

@zewelor This was already implicitly the case, as the most current version was referenced. Nevertheless, explicitly specifying a version is better anyway ;)

**Comment by zewelor** [comment]
If someone already had older version, of mithermometer and not using miflora. I dont think it will auto update ?

**Comment by cybe** [comment]
You're right on that one, there is [no auto update](https://github.com/zewelor/bt-mqtt-gateway/blob/85d7df4f0ba0023b66dec6584a7845115cdd0027/workers_manager.py#L185).

```
/ # pip install mithermometer==0.1.3
Collecting mithermometer==0.1.3
  Downloading https://files.pythonhosted.org/packages/8c/20/8022d9bc04077ef22e3afdd837ff78c1502338e68902753b4b45ddaf3756/mithermometer-0.1.3-py3-none-any.whl
Collecting btlewrap==0.0.4
  Downloading https://files.pythonhosted.org/packages/f9/3b/7175f20b87f69f254f94765b61d05ba51b5f1ebe6280ac994121c8895ab4/btlewrap-0.0.4.tar.gz
Installing collected packages: btlewrap, mithermometer
    Running setup.py install for btlewrap ... done
Successfully installed btlewrap-0.0.4 mithermometer-0.1.3

/ # pip install mithermometer
Requirement already satisfied: mithermometer in /usr/local/lib/python3.8/site-packages (0.1.3)
Requirement already satisfied: btlewrap==0.0.4 in /usr/local/lib/python3.8/site-packages (from mithermometer) (0.0.4)

/ # pip install mithermometer==0.1.4
Collecting mithermometer==0.1.4
  Downloading https://files.pythonhosted.org/packages/8c/f9/4e638f45a9996598acc601269ac6322a0d05af1646852ead20124a553c2c/mithermometer-0.1.4-py3-none-any.whl
Collecting btlewrap==0.0.9
  Downloading https://files.pythonhosted.org/packages/3b/5c/917ea5ea2586ee03cb5bd41007969ac665618d9ba96b538947dac231dbf2/btlewrap-0.0.9.tar.gz
Collecting typing<4,>=3
  Downloading https://files.pythonhosted.org/packages/fe/2e/b480ee1b75e6d17d2993738670e75c1feeb9ff7f64452153cf018051cc92/typing-3.7.4.1-py3-none-any.whl
Installing collected packages: typing, btlewrap, mithermometer
  Found existing installation: btlewrap 0.0.4
    Uninstalling btlewrap-0.0.4:
      Successfully uninstalled btlewrap-0.0.4
    Running setup.py install for btlewrap ... done
  Found existing installation: mithermometer 0.1.3
    Uninstalling mithermometer-0.1.3:
      Successfully uninstalled mithermometer-0.1.3
Successfully installed btlewrap-0.0.9 mithermometer-0.1.4 typing-3.7.4.1
```

**Comment by hechi** [comment]
Super thx @cybe and @zewelor i updated the repository and try it out :)
Btw. didn't see that in the README that you need additional packages, if you want to use the configuration of **mithermometer** or **btlewrap** for example. I just used `pip install -r requirements.txt` to install the deps and i was assuming that everything i need is installed ;)

**Comment by cybe** [comment]
@hechi `requirements.txt` only contain common requirements for all workers. This is by design: If one does not use a mithermometer device, that specific dependency is not installed. It will be installed [automatically at runtime](https://github.com/zewelor/bt-mqtt-gateway/blob/99ed094c874c093cc5e5622a0d57ccd7fc6d416f/workers/mithermometer.py#L9), when a mithermometer device is specified in the configuration file.

I don't like this approach, but I do not have a better idea ;)

**Comment by hechi** [comment]
Ok understood thx a lot and keep up the good work 👍
