### ISSUE TITLE
Problem install Miflora

### ISSUE THREAD

**Issue by dckiller51** [zewelor/bt-mqtt-gateway#109]
Now that I have fun with the nuts finder and the scale I try to install the miflora but it does not work. 

Do you have an idea with my log errors?

i tested live miflora demo.py on another install no link problem

`root@DietPi:/home/dietpi/bt-mqtt-gateway# ./gateway.py -d
2019-10-13 00:32:16,746 INFO bt-mqtt-gw gateway.py:61:<module> - Starting
2019-10-13 00:32:16,758 DEBUG bt-mqtt-gw.mqtt mqtt.py:30:__init__ - Setting LWT to: btgateway/lwt_topic
2019-10-13 00:32:18,072 DEBUG bt-mqtt-gw.workers_manager workers_manager.py:103:register_workers - Added miscale worker with 300 seconds interval and a 35 seconds timeout
2019-10-13 00:32:24,824 INFO bt-mqtt-gw.workers.blescanmulti blescanmulti.py:109:__init__ - Adding 2 blescanmulti devices
2019-10-13 00:32:24,838 DEBUG bt-mqtt-gw.workers_manager workers_manager.py:103:register_workers - Added blescanmulti worker with 60 seconds interval and a 35 seconds timeout
2019-10-13 00:32:28,373 INFO bt-mqtt-gw.workers.miflora miflora.py:23:_setup - Adding 1 miflora devices
2019-10-13 00:32:28,392 DEBUG bt-mqtt-gw.workers.miflora miflora.py:25:_setup - Adding miflora device 'anthurium_salon' (c4:7c:8d:6a:ca:fb)
Traceback (most recent call last):
  File "./gateway.py", line 67, in <module>
    manager.register_workers(global_topic_prefix).start(mqtt)
  File "/home/dietpi/bt-mqtt-gateway/workers_manager.py", line 88, in register_workers
    command_timeout, global_topic_prefix, **worker_config["args"]
  File "/home/dietpi/bt-mqtt-gateway/workers/base.py", line 7, in __init__
    self._setup()
  File "/home/dietpi/bt-mqtt-gateway/workers/miflora.py", line 28, in _setup
    "poller": MiFloraPoller(mac, BluepyBackend),
  File "/usr/local/lib/python3.5/dist-packages/miflora/miflora_poller.py", line 37, in __init__
    self._bt_interface = BluetoothInterface(backend, adapter)
TypeError: __init__() takes 2 positional arguments but 3 were given
`

**Comment by dckiller51** [comment]
Bad luck on the day I try miflora maj makes bugger.

Problem maj Miflora btlewrap==0.0.8

[https://github.com/open-homeautomation/miflora/issues/135](url)

Solved  
pip3 uninstall btlewrap
pip3 install btlewrap==0.0.4

[https://github.com/ChristianKuehnel/plantgateway/issues/40](url)
