### ISSUE TITLE
Cannot start gateway.py - error regarding paho mqtt

### ISSUE THREAD

**Issue by mtzro2003** [zewelor/bt-mqtt-gateway#113]
I'm trying to use the bt-mqtt-gateway to publish info from a [Xiaomi Temperature and Humidity Sensor](https://www.aliexpress.com/item/32843489009.html), but gateway.py cannot start:
```
$ sudo ./gateway.py -d
019-10-27 07:45:36,085 INFO bt-mqtt-gw gateway.py:61:<module> - Starting
2019-10-27 07:45:36,086 DEBUG bt-mqtt-gw.mqtt mqtt.py:30:__init__ - Setting LWT to: hostname/lwt_topic
2019-10-27 07:45:38,924 INFO bt-mqtt-gw.workers.mithermometer mithermometer.py:19:_setup - Adding 1 mithermometer devices
2019-10-27 07:45:38,925 DEBUG bt-mqtt-gw.workers.mithermometer mithermometer.py:21:_setup - Adding mithermometer device 'living_room' (58:2D:34:34:3B:DD)
2019-10-27 07:45:38,925 DEBUG bt-mqtt-gw.workers_manager workers_manager.py:93:register_workers - Added mithermometer config with a 2 seconds timeout
2019-10-27 07:45:38,925 DEBUG bt-mqtt-gw.workers_manager workers_manager.py:103:register_workers - Added mithermometer worker with 30 seconds interval and a 35 seconds timeout
Traceback (most recent call last):
  File "./gateway.py", line 67, in <module>
    manager.register_workers(global_topic_prefix).start(mqtt)
  File "/home/bt2mqtt/bt-mqtt-gateway/workers_manager.py", line 156, in start
    mqtt.callbacks_subscription(self._mqtt_callbacks)
  File "/home/bt2mqtt/bt-mqtt-gateway/mqtt.py", line 112, in callbacks_subscription
    self.mqttc.connect(self.hostname, port=self.port)
  File "/home/bt2mqtt/.local/lib/python3.6/site-packages/paho/mqtt/client.py", line 839, in connect
    return self.reconnect()
  File "/home/bt2mqtt/.local/lib/python3.6/site-packages/paho/mqtt/client.py", line 1009, in reconnect
    return self._send_connect(self._keepalive, self._clean_session)
  File "/home/bt2mqtt/.local/lib/python3.6/site-packages/paho/mqtt/client.py", line 2348, in _send_connect
    remaining_length += 2 + len(self._password)
TypeError: object of type 'int' has no len()
$
```
Here's the `config.yaml`:
```
$ cat config.yaml
mqtt:
  host: 192.168.200.100
  port: 1883
  username: bt2mqtt
  password: XXXXXXXXXXX
  #ca_cert: /etc/ssl/certs/ca-certificates.crt # Uncomment to enable MQTT TLS, update path to appropriate location.
  #ca_verify: False              # Verify TLS certificate chain and host, disable for testing with self-signed certificates, default to True
  topic_prefix: hostname         # All messages will have that prefix added, remove if you dont need this.
  client_id: bt-mqtt-gateway
  availability_topic: lwt_topic

manager:
  sensor_config:
    topic: openhab
    retain: true
  topic_subscription:
    update_all:
      topic: openhab/status
      payload: online
  command_timeout: 35           # Timeout for worker operations. Can be removed if the default of 35 seconds is sufficient.
  workers:
    mithermometer:
      args:
        devices:
          living_room: 58:2D:34:34:3B:DD
        topic_prefix: mithermometer
      update_interval: 30
```
Bluetooth is running properly, 'cause I can run `lescan` OK:
```
$ sudo hcitool lescan
LE Scan ...
50:AE:91:0A:00:D8 (unknown)
50:AE:91:0A:00:D8 (unknown)
79:67:88:3E:3D:F0 (unknown)
79:67:88:3E:3D:F0 (unknown)
20:DA:22:1C:FC:AA (unknown)
58:2D:34:34:3B:DD (unknown)
58:2D:34:34:3B:DD MJ_HT_V1
6E:B8:33:22:45:1F (unknown)
```

As far as I can tell, that error is regarding `paho mqtt` client, but I cannot figure it out.
I can publish mqtt messages with no problem using the configured host, username and password:
```
$ mosquitto_pub -h 192.168.200.100 -u bt2mqtt -P XXXXXXXXX -t hostname/mithermometer -m TEST
bt2mqtt@bt2mqtt:~/bt-mqtt-gateway$ mosquitto_pub -h 192.168.200.100 -u bt2mqtt -P 152814441511 -t hostname/mithermometer -m TEST22
bt2mqtt@bt2mqtt:~/bt-mqtt-gateway$
```
```
$ mosquitto_sub -h 192.168.200.100 -u bt2mqtt -P XXXXXXXXX -t hostname/mithermometer
TEST
TEST22
```

I'm open to any ideas... 
I'm pretty sure I'm missing something obvious...

**Comment by cybe** [comment]
If your password is only digits, it will be treated as a number type in yaml:
```
mqtt:
  password: 152814441511
```
paho mqtt expects a string type, though. You can force this by putting the number in `"`:
```
mqtt:
  password: "152814441511"
```

**Comment by mtzro2003** [comment]
Hot damn!
Was sure it was something simple!!!
Many thanks, indeed you are right!

**Comment by zewelor** [comment]
Added mqtt username and password cast to str, this should fix this for future, without need to quote password and / or username.
