### ISSUE TITLE
No module named bluepy

### ISSUE THREAD

**Issue by andreaconfa** [zewelor/bt-mqtt-gateway#126]
Hi all, 
i'm attempting to run bt-mqtt-gateway to detect some NUT beacons but when i execute the command "sudo ./gateway.py" e get this error 

```
22:11:38 Starting
Traceback (most recent call last):
  File "./gateway.py", line 67, in <module>
    manager.register_workers(global_topic_prefix).start(mqtt)
  File "/home/pi/bt-mqtt-gateway/workers_manager.py", line 81, in register_workers
    module_obj = importlib.import_module("workers.%s" % worker_name)
  File "/usr/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/pi/bt-mqtt-gateway/workers/blescanmulti.py", line 3, in <module>
    from bluepy.btle import Scanner, DefaultDelegate
ModuleNotFoundError: No module named 'bluepy'
```
what i can do? Thanks

**Comment by bbbenji** [comment]
`pip3 install bluepy`

**Comment by andreaconfa** [comment]
already tried, 


```
pi@raspberrypi:~ $ sudo pip3 install bluepy
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Requirement already satisfied: bluepy in /usr/local/lib/python3.7/dist-packages (1.3.0)
```

**Comment by andreaconfa** [comment]
My config is:


```
mqtt:
  host: 192.168.2.2
  port: 1883
  username: XXXXXX
  password: XXXXXX
  #ca_cert: /etc/ssl/certs/ca-certificates.crt # Uncomment to enable MQTT TLS, update path to appropriate location.
  #ca_verify: False              # Verify TLS certificate chain and host, disable for testing with self-signed certificates, default to True         # All messages will have that prefix added, remove if you dont need this.
  client_id: bt-mqtt-gateway
  availability_topic: lwt_topic

manager:
  workers:
      blescanmulti:
      args:
        devices:
          nut: D5:2A:E8:11:BA:0D
        topic_prefix: blescan
        available_payload: presente
        unavailable_payload: not_home
        available_timeout: 0
        unavailable_timeout: 60
        scan_timeout: 10
        scan_passive: true
```

**Comment by andreaconfa** [comment]
i think i have solved, it was a bad intentation of "args:"

**Comment by santhu2904** [comment]
> My config is:
> 
> ```
> mqtt:
>   host: 192.168.2.2
>   port: 1883
>   username: XXXXXX
>   password: XXXXXX
>   #ca_cert: /etc/ssl/certs/ca-certificates.crt # Uncomment to enable MQTT TLS, update path to appropriate location.
>   #ca_verify: False              # Verify TLS certificate chain and host, disable for testing with self-signed certificates, default to True         # All messages will have that prefix added, remove if you dont need this.
>   client_id: bt-mqtt-gateway
>   availability_topic: lwt_topic
> 
> manager:
>   workers:
>       blescanmulti:
>       args:
>         devices:
>           nut: D5:2A:E8:11:BA:0D
>         topic_prefix: blescan
>         available_payload: presente
>         unavailable_payload: not_home
>         available_timeout: 0
>         unavailable_timeout: 60
>         scan_timeout: 10
>         scan_passive: true
> ```



> 

How did you get rid of this?
