### ISSUE TITLE
Fatal error while executing worker command: BTLEException

### ISSUE THREAD

**Issue by hechi** [zewelor/bt-mqtt-gateway#140]
Hey guys, again thx for the hard work and keep going. I like your project and its awesome :)

**Describe the bug**
Regarding issue #108 the application is crashing with the message below. 
The same error appears if i execute it as a service

**To Reproduce**
Steps to reproduce the behaviour:
1. start application with `sudo ./gateway.py -d`
2. wait a few minutes. In my example approx. 3min
3. See the exception below

**Expected behaviour**
No crash after throwing the exception.

**Debug gateway logs**
```
pi@raspberrypi:~/bt-mqtt-gateway $ sudo ./gateway.py -d
2020-01-07 20:18:19,388 INFO bt-mqtt-gw gateway.py:61:<module> - Starting
2020-01-07 20:18:19,761 INFO bt-mqtt-gw.workers.thermostat thermostat.py:41:_setup - Adding 4 thermostat devices
2020-01-07 20:18:19,762 DEBUG bt-mqtt-gw.workers.thermostat thermostat.py:62:_setup - Adding thermostat device 'wohnzimmer' (AA:BB:CC:DD:EE:FF)
2020-01-07 20:18:19,762 DEBUG bt-mqtt-gw.workers.thermostat thermostat.py:62:_setup - Adding thermostat device 'badezimmer' (BB:CC:DD:EE:FF:GG)
2020-01-07 20:18:19,763 DEBUG bt-mqtt-gw.workers.thermostat thermostat.py:62:_setup - Adding thermostat device 'spielzimmer' (CC:DD:EE:FF:GG:HH)
2020-01-07 20:18:19,763 DEBUG bt-mqtt-gw.workers.thermostat thermostat.py:62:_setup - Adding thermostat device 'schlafzimmer' (DD:EE:FF:GG:HH:II)
2020-01-07 20:18:19,763 DEBUG bt-mqtt-gw.workers_manager workers_manager.py:96:register_workers - Added thermostat config with a 2 seconds timeout
2020-01-07 20:18:19,764 DEBUG bt-mqtt-gw.workers_manager workers_manager.py:106:register_workers - Added thermostat worker with 60 seconds interval and a 60 seconds timeout
2020-01-07 20:18:20,141 INFO bt-mqtt-gw.workers.blescanmulti blescanmulti.py:109:__init__ - Adding 2 blescanmulti devices
2020-01-07 20:18:20,142 DEBUG bt-mqtt-gw.workers_manager workers_manager.py:106:register_workers - Added blescanmulti worker with 60 seconds interval and a 60 seconds timeout
2020-01-07 20:18:20,145 DEBUG bt-mqtt-gw.mqtt mqtt.py:116:callbacks_subscription - Subscribing to: bluetoothGateway/thermostat/update_interval
2020-01-07 20:18:20,146 DEBUG bt-mqtt-gw.mqtt mqtt.py:116:callbacks_subscription - Subscribing to: bluetoothGateway/thermostat/+/+/set
2020-01-07 20:18:20,147 DEBUG bt-mqtt-gw.mqtt mqtt.py:116:callbacks_subscription - Subscribing to: bluetoothGateway/blescan/update_interval
2020-01-07 20:18:20,148 DEBUG bt-mqtt-gw.mqtt mqtt.py:116:callbacks_subscription - Subscribing to: bluetoothGateway/homeassistant/status
2020-01-07 20:18:20,152 DEBUG bt-mqtt-gw.workers_manager workers_manager.py:67:execute - Execution result of command ThermostatWorker.config: <message contain to much information so removed it>
2020-01-07 20:18:20,168 DEBUG bt-mqtt-gw.workers_manager workers_manager.py:174:update_all - Updating all workers
2020-01-07 20:18:20,169 INFO bt-mqtt-gw.workers.thermostat thermostat.py:192:status_update - Updating 4 thermostat devices
2020-01-07 20:18:20,170 DEBUG bt-mqtt-gw.workers.thermostat thermostat.py:194:status_update - Updating thermostat device 'wohnzimmer' (AA:BB:CC:DD:EE:FF)
2020-01-07 20:18:31,801 ERROR bt-mqtt-gw.workers.thermostat logger.py:50:log_exception - Error during update of thermostat device 'wohnzimmer' (AA:BB:CC:DD:EE:FF): BTLEException
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/eq3bt/connection.py", line 36, in __enter__
    self._conn.connect(self._mac)
  File "/usr/local/lib/python3.5/dist-packages/bluepy/btle.py", line 416, in connect
    self._connect(addr, addrType, iface)
  File "/usr/local/lib/python3.5/dist-packages/bluepy/btle.py", line 410, in _connect
    "Failed to connect to peripheral %s, addr type: %s" % (addr, addrType))
bluepy.btle.BTLEException: Failed to connect to peripheral AA:BB:CC:DD:EE:FF, addr type: public

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pi/bt-mqtt-gateway/workers/thermostat.py", line 197, in status_update
    thermostat.update()
  File "/usr/local/lib/python3.5/dist-packages/eq3bt/eq3btsmart.py", line 163, in update
    self._conn.make_request(PROP_WRITE_HANDLE, value)
  File "/usr/local/lib/python3.5/dist-packages/eq3bt/connection.py", line 71, in make_request
    with self:
  File "/usr/local/lib/python3.5/dist-packages/eq3bt/connection.py", line 40, in __enter__
    self._conn.connect(self._mac)
  File "/usr/local/lib/python3.5/dist-packages/bluepy/btle.py", line 416, in connect
    self._connect(addr, addrType, iface)
  File "/usr/local/lib/python3.5/dist-packages/bluepy/btle.py", line 410, in _connect
    "Failed to connect to peripheral %s, addr type: %s" % (addr, addrType))
bluepy.btle.BTLEException: Failed to connect to peripheral AA:BB:CC:DD:EE:FF, addr type: public
2020-01-07 20:18:31,810 DEBUG bt-mqtt-gw.workers.thermostat thermostat.py:194:status_update - Updating thermostat device 'badezimmer' (BB:CC:DD:EE:FF:GG)
2020-01-07 20:19:20,170 ERROR bt-mqtt-gw logger.py:50:log_exception - Execution of command ThermostatWorker.status_update timed out after 60 seconds
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/eq3bt/connection.py", line 36, in __enter__
    self._conn.connect(self._mac)
  File "/usr/local/lib/python3.5/dist-packages/bluepy/btle.py", line 416, in connect
    self._connect(addr, addrType, iface)
  File "/usr/local/lib/python3.5/dist-packages/bluepy/btle.py", line 410, in _connect
    "Failed to connect to peripheral %s, addr type: %s" % (addr, addrType))
bluepy.btle.BTLEException: Failed to connect to peripheral BB:CC:DD:EE:FF:GG, addr type: public

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./gateway.py", line 73, in <module>
    mqtt.publish(_WORKERS_QUEUE.get(timeout=10).execute())
  File "/home/pi/bt-mqtt-gateway/workers_manager.py", line 65, in execute
    raise e
  File "/home/pi/bt-mqtt-gateway/workers_manager.py", line 55, in execute
    for message in self._callback(*self._args):
  File "/home/pi/bt-mqtt-gateway/workers/thermostat.py", line 197, in status_update
    thermostat.update()
  File "/usr/local/lib/python3.5/dist-packages/eq3bt/eq3btsmart.py", line 163, in update
    self._conn.make_request(PROP_WRITE_HANDLE, value)
  File "/usr/local/lib/python3.5/dist-packages/eq3bt/connection.py", line 71, in make_request
    with self:
  File "/usr/local/lib/python3.5/dist-packages/eq3bt/connection.py", line 40, in __enter__
    self._conn.connect(self._mac)
  File "/usr/local/lib/python3.5/dist-packages/bluepy/btle.py", line 416, in connect
    self._connect(addr, addrType, iface)
  File "/usr/local/lib/python3.5/dist-packages/bluepy/btle.py", line 406, in _connect
    rsp = self._getResp('stat')
  File "/usr/local/lib/python3.5/dist-packages/bluepy/btle.py", line 377, in _getResp
    resp = self._waitResp(wantType + ['ntfy', 'ind'], timeout)
  File "/usr/local/lib/python3.5/dist-packages/bluepy/btle.py", line 319, in _waitResp
    rv = self._helper.stdout.readline()
  File "/usr/local/lib/python3.5/dist-packages/interruptingcow/__init__.py", line 74, in handler
    raise exception
exceptions.WorkerTimeoutError: Execution of command ThermostatWorker.status_update timed out after 60 seconds
2020-01-07 20:19:20,183 INFO bt-mqtt-gw.workers.blescanmulti blescanmulti.py:112:status_update - Updating 2 blescanmulti devices
2020-01-07 20:19:20,574 DEBUG bt-mqtt-gw.workers.blescanmulti blescanmulti.py:20:handleDiscovery - Discovered new device: DD:EE:FF:GG:HH:II
2020-01-07 20:19:21,210 DEBUG bt-mqtt-gw.workers.blescanmulti blescanmulti.py:20:handleDiscovery - Discovered new device: CC:DD:EE:FF:GG:HH
2020-01-07 20:19:24,872 DEBUG bt-mqtt-gw.workers.blescanmulti blescanmulti.py:20:handleDiscovery - Discovered new device: AA:BB:CC:DD:EE:FF
2020-01-07 20:19:40,241 DEBUG bt-mqtt-gw.workers_manager workers_manager.py:67:execute - Execution result of command BlescanmultiWorker.status_update: [{'payload': 'home', 'topic': 'blescan/presence/itag01'}, {'payload': '-47', 'topic': 'blescan/presence/itag01/rssi'}]
2020-01-07 20:19:40,244 INFO bt-mqtt-gw.workers.thermostat thermostat.py:192:status_update - Updating 4 thermostat devices
2020-01-07 20:19:40,245 DEBUG bt-mqtt-gw.workers.thermostat thermostat.py:194:status_update - Updating thermostat device 'wohnzimmer' (AA:BB:CC:DD:EE:FF)
2020-01-07 20:19:56,995 ERROR bt-mqtt-gw.workers.thermostat logger.py:50:log_exception - Error during update of thermostat device 'wohnzimmer' (AA:BB:CC:DD:EE:FF): BTLEException
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/eq3bt/connection.py", line 36, in __enter__
    self._conn.connect(self._mac)
  File "/usr/local/lib/python3.5/dist-packages/bluepy/btle.py", line 416, in connect
    self._connect(addr, addrType, iface)
  File "/usr/local/lib/python3.5/dist-packages/bluepy/btle.py", line 410, in _connect
    "Failed to connect to peripheral %s, addr type: %s" % (addr, addrType))
bluepy.btle.BTLEException: Failed to connect to peripheral AA:BB:CC:DD:EE:FF, addr type: public

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pi/bt-mqtt-gateway/workers/thermostat.py", line 197, in status_update
    thermostat.update()
  File "/usr/local/lib/python3.5/dist-packages/eq3bt/eq3btsmart.py", line 163, in update
    self._conn.make_request(PROP_WRITE_HANDLE, value)
  File "/usr/local/lib/python3.5/dist-packages/eq3bt/connection.py", line 71, in make_request
    with self:
  File "/usr/local/lib/python3.5/dist-packages/eq3bt/connection.py", line 40, in __enter__
    self._conn.connect(self._mac)
  File "/usr/local/lib/python3.5/dist-packages/bluepy/btle.py", line 416, in connect
    self._connect(addr, addrType, iface)
  File "/usr/local/lib/python3.5/dist-packages/bluepy/btle.py", line 410, in _connect
    "Failed to connect to peripheral %s, addr type: %s" % (addr, addrType))
bluepy.btle.BTLEException: Failed to connect to peripheral AA:BB:CC:DD:EE:FF, addr type: public
2020-01-07 20:19:57,001 DEBUG bt-mqtt-gw.workers.thermostat thermostat.py:194:status_update - Updating thermostat device 'badezimmer' (BB:CC:DD:EE:FF:GG)
2020-01-07 20:20:40,245 ERROR bt-mqtt-gw logger.py:50:log_exception - Execution of command ThermostatWorker.status_update timed out after 60 seconds
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/eq3bt/connection.py", line 36, in __enter__
    self._conn.connect(self._mac)
  File "/usr/local/lib/python3.5/dist-packages/bluepy/btle.py", line 416, in connect
    self._connect(addr, addrType, iface)
  File "/usr/local/lib/python3.5/dist-packages/bluepy/btle.py", line 410, in _connect
    "Failed to connect to peripheral %s, addr type: %s" % (addr, addrType))
bluepy.btle.BTLEException: Failed to connect to peripheral BB:CC:DD:EE:FF:GG, addr type: public

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./gateway.py", line 73, in <module>
    mqtt.publish(_WORKERS_QUEUE.get(timeout=10).execute())
  File "/home/pi/bt-mqtt-gateway/workers_manager.py", line 65, in execute
    raise e
  File "/home/pi/bt-mqtt-gateway/workers_manager.py", line 55, in execute
    for message in self._callback(*self._args):
  File "/home/pi/bt-mqtt-gateway/workers/thermostat.py", line 197, in status_update
    thermostat.update()
  File "/usr/local/lib/python3.5/dist-packages/eq3bt/eq3btsmart.py", line 163, in update
    self._conn.make_request(PROP_WRITE_HANDLE, value)
  File "/usr/local/lib/python3.5/dist-packages/eq3bt/connection.py", line 71, in make_request
    with self:
  File "/usr/local/lib/python3.5/dist-packages/eq3bt/connection.py", line 40, in __enter__
    self._conn.connect(self._mac)
  File "/usr/local/lib/python3.5/dist-packages/bluepy/btle.py", line 416, in connect
    self._connect(addr, addrType, iface)
  File "/usr/local/lib/python3.5/dist-packages/bluepy/btle.py", line 406, in _connect
    rsp = self._getResp('stat')
  File "/usr/local/lib/python3.5/dist-packages/bluepy/btle.py", line 377, in _getResp
    resp = self._waitResp(wantType + ['ntfy', 'ind'], timeout)
  File "/usr/local/lib/python3.5/dist-packages/bluepy/btle.py", line 319, in _waitResp
    rv = self._helper.stdout.readline()
  File "/usr/local/lib/python3.5/dist-packages/interruptingcow/__init__.py", line 74, in handler
    raise exception
exceptions.WorkerTimeoutError: Execution of command ThermostatWorker.status_update timed out after 60 seconds
2020-01-07 20:20:40,252 INFO bt-mqtt-gw.workers.blescanmulti blescanmulti.py:112:status_update - Updating 2 blescanmulti devices
2020-01-07 20:20:41,367 DEBUG bt-mqtt-gw.workers.blescanmulti blescanmulti.py:20:handleDiscovery - Discovered new device: CC:DD:EE:FF:GG:HH
2020-01-07 20:20:41,711 DEBUG bt-mqtt-gw.workers.blescanmulti blescanmulti.py:20:handleDiscovery - Discovered new device: DD:EE:FF:GG:HH:II
2020-01-07 20:20:42,010 DEBUG bt-mqtt-gw.workers.blescanmulti blescanmulti.py:20:handleDiscovery - Discovered new device: AA:BB:CC:DD:EE:FF
2020-01-07 20:21:00,171 DEBUG bt-mqtt-gw.workers.blescanmulti blescanmulti.py:20:handleDiscovery - Discovered new device: BB:CC:DD:EE:FF:GG
2020-01-07 20:21:00,286 ERROR bt-mqtt-gw logger.py:50:log_exception - Fatal error while executing worker command: BTLEException
Traceback (most recent call last):
  File "./gateway.py", line 73, in <module>
    mqtt.publish(_WORKERS_QUEUE.get(timeout=10).execute())
  File "/home/pi/bt-mqtt-gateway/workers_manager.py", line 58, in execute
    messages = self._callback(*self._args)
  File "/home/pi/bt-mqtt-gateway/workers/blescanmulti.py", line 114, in status_update
    float(self.scan_timeout), passive=booleanize(self.scan_passive)
  File "/usr/local/lib/python3.5/dist-packages/bluepy/btle.py", line 736, in scan
    self.stop()
  File "/usr/local/lib/python3.5/dist-packages/bluepy/btle.py", line 685, in stop
    self._mgmtCmd(self._cmd()+"end")
  File "/usr/local/lib/python3.5/dist-packages/bluepy/btle.py", line 279, in _mgmtCmd
    rsp = self._waitResp('mgmt')
  File "/usr/local/lib/python3.5/dist-packages/bluepy/btle.py", line 334, in _waitResp
    raise BTLEException(BTLEException.DISCONNECTED, "Device disconnected")
bluepy.btle.BTLEException: Device disconnected
Traceback (most recent call last):
  File "./gateway.py", line 91, in <module>
    raise e
  File "./gateway.py", line 73, in <module>
    mqtt.publish(_WORKERS_QUEUE.get(timeout=10).execute())
  File "/home/pi/bt-mqtt-gateway/workers_manager.py", line 58, in execute
    messages = self._callback(*self._args)
  File "/home/pi/bt-mqtt-gateway/workers/blescanmulti.py", line 114, in status_update
    float(self.scan_timeout), passive=booleanize(self.scan_passive)
  File "/usr/local/lib/python3.5/dist-packages/bluepy/btle.py", line 736, in scan
    self.stop()
  File "/usr/local/lib/python3.5/dist-packages/bluepy/btle.py", line 685, in stop
    self._mgmtCmd(self._cmd()+"end")
  File "/usr/local/lib/python3.5/dist-packages/bluepy/btle.py", line 279, in _mgmtCmd
    rsp = self._waitResp('mgmt')
  File "/usr/local/lib/python3.5/dist-packages/bluepy/btle.py", line 334, in _waitResp
    raise BTLEException(BTLEException.DISCONNECTED, "Device disconnected")
bluepy.btle.BTLEException: Device disconnected
pi@raspberrypi:~/bt-mqtt-gateway $
```
**Server (please complete the following information):**
 - OS: Linux
 - Distro: Raspbian 
 - Version 9.3
 - Python 3.5.3
 - Raspberry Pi information
```
        Raspberry Pi Informationen
===========================================
Model : Raspberry Pi 3 Model B Rev 1.2
==========================================
Prozessor : ARMv7 Processor rev 4 (v7l)
===========================================
CPU-Kerne : 4     CPU-Architektur : 7
===========================================
Hardware : BCM2835   Revision : a02082
===========================================
```
**Additional context**
my config.yaml
```
mqtt:
  host: 192.168.1.2
  port: 1883
  username: mqtt
  password: supersecretpassword12345
  topic_prefix: bluetoothGateway

manager:
  sensor_config:
    topic: homeassistant
    retain: true
  topic_subscription:
    update_all:
      topic: homeassistant/status
      payload: online
  command_timeout: 60
  workers:
    thermostat:
      args:
        devices:
           wohnzimmer: AA:BB:CC:DD:EE:FF
           schlafzimmer: DD:EE:FF:GG:HH:II
           badezimmer: BB:CC:DD:EE:FF:GG
           spielzimmer: CC:DD:EE:FF:GG:HH
        topic_prefix: thermostat
      topic_subscription: thermostat/+/+/set
      command_timeout: 60
      update_interval: 60
    blescanmulti:
      args:
        devices:
          itag01: EE:FF:GG:HH:II:JJ
        topic_prefix: blescan
        available_payload: home
        unavailable_payload: not_home
        available_timeout: 0
        unavailable_timeout: 60
        scan_timeout: 20
        scan_passive: true
      update_interval: 60
```

**Comment by hechi** [comment]
So as far as I understood it the `raise e` line 91 in [gateway.py](../blob/master/gateway.py) will terminate the application. So removing it would be possible or catching this exception 🤷‍♂ 

https://docs.python.org/3/tutorial/errors.html#raising-exceptions

**Comment by zewelor** [comment]
Try this fix: https://github.com/zewelor/bt-mqtt-gateway/pull/141

**Comment by hechi** [comment]
Hey, thanks for the super fast answer and fix. Sadly it worked just a bit :(
```
2020-01-08 19:14:01,868 ERROR bt-mqtt-gw logger.py:50:log_exception - Fatal error while executing worker command: BrokenPipeError
Traceback (most recent call last):
  File "./gateway.py", line 73, in <module>
    mqtt.publish(_WORKERS_QUEUE.get(timeout=10).execute())
  File "/home/pi/bt-mqtt-gateway/workers_manager.py", line 58, in execute
    messages = self._callback(*self._args)
  File "/home/pi/bt-mqtt-gateway/workers/blescanmulti.py", line 120, in status_update
    float(self.scan_timeout), passive=booleanize(self.scan_passive)
  File "/usr/local/lib/python3.5/dist-packages/bluepy/btle.py", line 734, in scan
    self.start(passive=passive)
  File "/usr/local/lib/python3.5/dist-packages/bluepy/btle.py", line 672, in start
    self._mgmtCmd("le on")
  File "/usr/local/lib/python3.5/dist-packages/bluepy/btle.py", line 278, in _mgmtCmd
    self._writeCmd(cmd + '\n')
  File "/usr/local/lib/python3.5/dist-packages/bluepy/btle.py", line 275, in _writeCmd
    self._helper.stdin.flush()
BrokenPipeError: [Errno 32] Broken pipe
Traceback (most recent call last):
  File "./gateway.py", line 91, in <module>
    raise e
  File "./gateway.py", line 73, in <module>
    mqtt.publish(_WORKERS_QUEUE.get(timeout=10).execute())
  File "/home/pi/bt-mqtt-gateway/workers_manager.py", line 58, in execute
    messages = self._callback(*self._args)
  File "/home/pi/bt-mqtt-gateway/workers/blescanmulti.py", line 120, in status_update
    float(self.scan_timeout), passive=booleanize(self.scan_passive)
  File "/usr/local/lib/python3.5/dist-packages/bluepy/btle.py", line 734, in scan
    self.start(passive=passive)
  File "/usr/local/lib/python3.5/dist-packages/bluepy/btle.py", line 672, in start
    self._mgmtCmd("le on")
  File "/usr/local/lib/python3.5/dist-packages/bluepy/btle.py", line 278, in _mgmtCmd
    self._writeCmd(cmd + '\n')
  File "/usr/local/lib/python3.5/dist-packages/bluepy/btle.py", line 275, in _writeCmd
    self._helper.stdin.flush()
BrokenPipeError: [Errno 32] Broken pipe
```
It seems that its coming from the same line/module

**Comment by zewelor** [comment]
Looks like some problem with bluetooth adapter ? That could explain why noone else reported issue with blemultiscanner. Maybe you need to debug in logs etc, maybe some clue about whats goin on ? Any other process, uses bluetooth at the same time ? I could also catch that error, but still something is wrong / bad with hardware or setup, that can cause missing bluetooth updates etc, on other workers. Which Bluez version are you using ?

**Comment by hechi** [comment]
hmmm... I am running bluez `Version: 5.43-2+rpt2+deb9u2`. I updated the **bulepy** package from version 1.2.0 to 1.3.0. 
I checked **syslog** **dmesg** and **kernel.log** nothing suspicious and if then it should also affect the other bluetooth devices right? For e.x. thermostat worker. The devices are a bit far away that's why the sometimes loose connection.

**Comment by zewelor** [comment]
I would start with bluez upgrade. This version is very old. Try minimum 5.50 or newer ( https://github.com/zewelor/bt-mqtt-gateway/wiki/Upgrade-Bluez-on-Raspbian ). Why it works on thermostat is probably because blemultiscan uses passive scanning, and thermostat only reads form device, probalby there is some error in rpi bluetooth in LE mode and some operations. I got random errors on my rpizw, on original bluez, and after upgrading it, its much more stable.

**Comment by hechi** [comment]
Ok, thx a lot I will try your suggestion :) and keep going good work.
