### ISSUE TITLE
Gateway not starting

### ISSUE THREAD

**Issue by lhusoey** [zewelor/bt-mqtt-gateway#153]
**Describe the bug**
(venv) pi@raspberrypi:~/bt-mqtt-gateway $ sudo ./gateway.py                     09:10:33 Starting
09:10:35 Adding 1 blescanmulti devices
Traceback (most recent call last):
  File "./gateway.py", line 83, in <module>
    manager.start(mqtt)
  File "/home/pi/bt-mqtt-gateway/workers_manager.py", line 157, in start
    mqtt.callbacks_subscription(self._mqtt_callbacks)
  File "/home/pi/bt-mqtt-gateway/mqtt.py", line 112, in callbacks_subscription
    self.mqttc.connect(self.hostname, port=self.port)
  File "/usr/local/lib/python3.7/dist-packages/paho/mqtt/client.py", line 937, in connect
    return self.reconnect()
  File "/usr/local/lib/python3.7/dist-packages/paho/mqtt/client.py", line 1071, in reconnect
    sock = self._create_socket_connection()
  File "/usr/local/lib/python3.7/dist-packages/paho/mqtt/client.py", line 3522, in _create_socket_connection
    return socket.create_connection(addr, source_address=source, timeout=self._keepalive)
  File "/usr/lib/python3.7/socket.py", line 727, in create_connection
    raise err
  File "/usr/lib/python3.7/socket.py", line 716, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

**To Reproduce**
sudo ./gateway.py  

**Expected behavior**
gateway to start

**Config**
mqtt:
  host: 192.168.10.102
  port: 1883
  username: user
  password: password
  #ca_cert: /etc/ssl/certs/ca-certificates.crt # Uncomment to enable MQTT TLS, update path to appropriate location.
  #ca_verify: False              # Verify TLS certificate chain and host, disable for testing with self-signed certificates, default to True         # All messages will have that prefix added, remove if you dont need this.
  client_id: bt-mqtt-gateway
  availability_topic: lwt_topic

manager:
  workers:
    blescanmulti:
      args:
        devices:
          nut: DC:0D:30:00:01:21
        topic_prefix: blescan
        available_payload: presente
        unavailable_payload: not_home
        available_timeout: 0
        unavailable_timeout: 60
        scan_timeout: 10
        scan_passive: true
      update_interval: 1800
**Debug gateway logs**
(venv) pi@raspberrypi:~/bt-mqtt-gateway $ sudo ./gateway.py -d                  2020-02-17 09:13:11,095 INFO bt-mqtt-gw gateway.py:76:<module> - Starting
2020-02-17 09:13:11,097 DEBUG bt-mqtt-gw.mqtt mqtt.py:30:__init__ - Setting LWT to: lwt_topic
2020-02-17 09:13:13,440 INFO bt-mqtt-gw.workers.blescanmulti blescanmulti.py:109:__init__ - Adding 1 blescanmulti devices
2020-02-17 09:13:13,440 DEBUG bt-mqtt-gw.workers_manager workers_manager.py:106:register_workers - Added blescanmulti worker with 1800 seconds interval and a 35 seconds timeout
Traceback (most recent call last):
  File "./gateway.py", line 83, in <module>
    manager.start(mqtt)
  File "/home/pi/bt-mqtt-gateway/workers_manager.py", line 157, in start
    mqtt.callbacks_subscription(self._mqtt_callbacks)
  File "/home/pi/bt-mqtt-gateway/mqtt.py", line 112, in callbacks_subscription
    self.mqttc.connect(self.hostname, port=self.port)
  File "/usr/local/lib/python3.7/dist-packages/paho/mqtt/client.py", line 937, in connect
    return self.reconnect()
  File "/usr/local/lib/python3.7/dist-packages/paho/mqtt/client.py", line 1071, in reconnect
    sock = self._create_socket_connection()
  File "/usr/local/lib/python3.7/dist-packages/paho/mqtt/client.py", line 3522, in _create_socket_connection
    return socket.create_connection(addr, source_address=source, timeout=self._keepalive)
  File "/usr/lib/python3.7/socket.py", line 727, in create_connection
    raise err
  File "/usr/lib/python3.7/socket.py", line 716, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

**Server (please complete the following information):**

 - Distro: Raspian

**Comment by zewelor** [comment]
as error says, it cannot connect to mqtt server provided, check port / ip / login or try via mosquitto_sub to connect there

**Comment by lhusoey** [comment]
Hi, thanks for the quick reply :)

I am running a MQTT Broker on my Homey Pro. Have now updated Ip to match Homey Pro Ip and the service seems to start. But something still seems to be wrong.
When starting with debug this is showing.

pi@raspberrypi:~/bt-mqtt-gateway $ sudo ./gateway.py -d
2020-02-17 11:25:04,524 INFO bt-mqtt-gw gateway.py:76:<module> - Starting
2020-02-17 11:25:04,525 DEBUG bt-mqtt-gw.mqtt mqtt.py:30:__init__ - Setting LWT to: lwt_topic
2020-02-17 11:25:06,647 INFO bt-mqtt-gw.workers.blescanmulti blescanmulti.py:109:__init__ - Adding 1 blescanmulti devices
2020-02-17 11:25:06,647 DEBUG bt-mqtt-gw.workers_manager workers_manager.py:106:register_workers - Added blescanmulti worker with 10 seconds interval and a 35 seconds timeout
2020-02-17 11:25:06,665 DEBUG bt-mqtt-gw.mqtt mqtt.py:116:callbacks_subscription - Subscribing to: blescan/update_interval
2020-02-17 11:25:06,670 DEBUG bt-mqtt-gw.workers_manager workers_manager.py:172:update_all - Updating all workers
2020-02-17 11:25:06,671 INFO bt-mqtt-gw.workers.blescanmulti blescanmulti.py:114:status_update - Updating 1 blescanmulti devices
2020-02-17 11:25:41,672 ERROR bt-mqtt-gw logger.py:50:log_exception - Execution of command BlescanmultiWorker.status_update timed out after 35 seconds
Traceback (most recent call last):
  File "./gateway.py", line 89, in <module>
    mqtt.publish(_WORKERS_QUEUE.get(timeout=10).execute())
  File "/home/pi/bt-mqtt-gateway/workers_manager.py", line 65, in execute
    raise e
  File "/home/pi/bt-mqtt-gateway/workers_manager.py", line 58, in execute
    messages = self._callback(*self._args)
  File "/home/pi/bt-mqtt-gateway/workers/blescanmulti.py", line 120, in status_update
    float(self.scan_timeout), passive=booleanize(self.scan_passive)
  File "/usr/local/lib/python3.7/dist-packages/bluepy/btle.py", line 854, in scan
    self.stop()
  File "/usr/local/lib/python3.7/dist-packages/bluepy/btle.py", line 803, in stop
    self._mgmtCmd(self._cmd()+"end")
  File "/usr/local/lib/python3.7/dist-packages/bluepy/btle.py", line 309, in _mgmtCmd
    rsp = self._waitResp('mgmt')
  File "/usr/local/lib/python3.7/dist-packages/bluepy/btle.py", line 347, in _waitResp
    rv = self._helper.stdout.readline()
  File "/usr/local/lib/python3.7/dist-packages/interruptingcow/__init__.py", line 74, in handler
    raise exception
exceptions.WorkerTimeoutError: Execution of command BlescanmultiWorker.status_update timed out after 35 seconds
2020-02-17 11:25:41,680 INFO bt-mqtt-gw.workers.blescanmulti blescanmulti.py:114:status_update - Updating 1 blescanmulti devices
^C2020-02-17 11:25:42,855 INFO bt-mqtt-gw gateway.py:101:<module> - Finish current jobs and shut down. If you need force exit use kill

**Comment by zewelor** [comment]
Probably old bluez, try to upgrade it and try again https://github.com/zewelor/bt-mqtt-gateway/wiki/Upgrade-Bluez-on-Raspbian

**Comment by lhusoey** [comment]
Updated bluez according to instructions in link.
Seems to be working :)

**Comment by lhusoey** [comment]
Hi,

Still some errors after updating bluez.

2020-02-18 14:34:28,968 DEBUG bt-mqtt-gw.workers_manager workers_manager.py:67:execute - Execution result of command BlescanmultiWorker.status_update: [{'topic': 'blescan/presence/bmwi3', 'payload': 'home'}, {'topic': 'blescan/presence/bmwi3/rssi', 'payload': '-97'}]
2020-02-18 14:34:28,972 INFO bt-mqtt-gw.workers.blescanmulti blescanmulti.py:114:status_update - Updating 2 blescanmulti devices
2020-02-18 14:34:29,035 DEBUG bt-mqtt-gw.workers.blescanmulti blescanmulti.py:100:handleDiscovery - Discovered new device: 2c:d1:f3:c0:d9:60
2020-02-18 14:34:29,042 DEBUG bt-mqtt-gw.workers.blescanmulti blescanmulti.py:100:handleDiscovery - Discovered new device: 57:b4:0b:3e:58:4d
2020-02-18 14:34:29,083 DEBUG bt-mqtt-gw.workers.blescanmulti blescanmulti.py:100:handleDiscovery - Discovered new device: 04:4b:ed:a7:e1:e8
2020-02-18 14:34:29,102 DEBUG bt-mqtt-gw.workers.blescanmulti blescanmulti.py:100:handleDiscovery - Discovered new device: 3d:96:1b:4f:2f:d0
2020-02-18 14:34:29,195 DEBUG bt-mqtt-gw.workers.blescanmulti blescanmulti.py:100:handleDiscovery - Discovered new device: f0:99:19:16:50:37
2020-02-18 14:34:29,447 DEBUG bt-mqtt-gw.workers.blescanmulti blescanmulti.py:100:handleDiscovery - Discovered new device: 6a:a2:66:4b:3b:ba
2020-02-18 14:34:29,829 DEBUG bt-mqtt-gw.workers.blescanmulti blescanmulti.py:100:handleDiscovery - Discovered new device: dc:0d:30:00:01:27
--- Logging error ---
Traceback (most recent call last):
  File "/home/pi/bt-mqtt-gateway/workers/blescanmulti.py", line 120, in status_update
    float(self.scan_timeout), passive=booleanize(self.scan_passive)
  File "/usr/local/lib/python3.7/dist-packages/bluepy/btle.py", line 854, in scan
    self.stop()
  File "/usr/local/lib/python3.7/dist-packages/bluepy/btle.py", line 803, in stop
    self._mgmtCmd(self._cmd()+"end")
  File "/usr/local/lib/python3.7/dist-packages/bluepy/btle.py", line 312, in _mgmtCmd
    raise BTLEManagementError("Failed to execute management command '%s'" % (cmd), rsp)
bluepy.btle.BTLEManagementError: Failed to execute management command 'pasvend'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.7/logging/__init__.py", line 1034, in emit
    msg = self.format(record)
  File "/usr/lib/python3.7/logging/__init__.py", line 880, in format
    return fmt.format(record)
  File "/usr/lib/python3.7/logging/__init__.py", line 619, in format
    record.message = record.getMessage()
  File "/usr/lib/python3.7/logging/__init__.py", line 380, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "./gateway.py", line 89, in <module>
    mqtt.publish(_WORKERS_QUEUE.get(timeout=10).execute())
  File "/home/pi/bt-mqtt-gateway/workers_manager.py", line 58, in execute
    messages = self._callback(*self._args)
  File "/home/pi/bt-mqtt-gateway/workers/blescanmulti.py", line 135, in status_update
    suppress=True,
  File "/home/pi/bt-mqtt-gateway/logger.py", line 50, in log_exception
    logger.exception(message, *args, **kwargs)
Message: 'Error during update (%s)'
Arguments: ('blescanmulti', 'BTLEManagementError')
2020-02-18 14:34:44,011 DEBUG bt-mqtt-gw.workers_manager workers_manager.py:67:execute - Execution result of command BlescanmultiWorker.status_update: []
2020-02-18 14:34:44,013 INFO bt-mqtt-gw.workers.blescanmulti blescanmulti.py:114:status_update - Updating 2 blescanmulti devices


As you can see it is scanning fine and suddely this fault is coming. CAn be like this for seconds or minutes and then go back to scanning BLE.

Any idea?

Best regards
Lidvar

**Comment by zewelor** [comment]
Never saw that error. Did you try googling ?

**Comment by lhusoey** [comment]
Hi,

I found that it was the onboard bluetooth that caused the error.
I disable the onboar and use an USB BT dongle instead. And this error is gone. 

Now i have a new issue.

Bluetooth devices is discovered without problem, but when a device is exiting and therfore supposed to send "away" mqtt message i get an error and scanning stops.

2020-02-21 09:20:02,829 DEBUG bt-mqtt-gw.workers_manager workers_manager.py:67:execute - Execution result of command BlescanmultiWorker.status_update: []
2020-02-21 09:20:02,830 INFO bt-mqtt-gw.workers.blescanmulti blescanmulti.py:114:status_update - Updating 2 blescanmulti devices
2020-02-21 09:20:02,888 DEBUG bt-mqtt-gw.workers.blescanmulti blescanmulti.py:100:handleDiscovery - Discovered new device: 11:21:97:4c:7c:41
2020-02-21 09:20:02,947 DEBUG bt-mqtt-gw.workers.blescanmulti blescanmulti.py:100:handleDiscovery - Discovered new device: 50:fb:6e:c2:f0:f4
2020-02-21 09:20:03,205 DEBUG bt-mqtt-gw.workers.blescanmulti blescanmulti.py:100:handleDiscovery - Discovered new device: 40:e1:0b:76:54:5a
2020-02-21 09:20:03,259 DEBUG bt-mqtt-gw.workers.blescanmulti blescanmulti.py:100:handleDiscovery - Discovered new device: dc:0d:30:00:01:27
2020-02-21 09:20:03,937 DEBUG bt-mqtt-gw.workers.blescanmulti blescanmulti.py:100:handleDiscovery - Discovered new device: 04:4b:ed:a7:e1:e8
2020-02-21 09:20:04,479 DEBUG bt-mqtt-gw.workers.blescanmulti blescanmulti.py:100:handleDiscovery - Discovered new device: 2c:d1:f3:c0:d9:60
2020-02-21 09:20:12,863 DEBUG bt-mqtt-gw.workers_manager workers_manager.py:67:execute - Execution result of command BlescanmultiWorker.status_update: []
2020-02-21 09:20:12,864 INFO bt-mqtt-gw.workers.blescanmulti blescanmulti.py:114:status_update - Updating 2 blescanmulti devices
2020-02-21 09:20:12,903 DEBUG bt-mqtt-gw.workers.blescanmulti blescanmulti.py:100:handleDiscovery - Discovered new device: 11:21:97:4c:7c:41
2020-02-21 09:20:13,022 DEBUG bt-mqtt-gw.workers.blescanmulti blescanmulti.py:100:handleDiscovery - Discovered new device: 50:fb:6e:c2:f0:f4
2020-02-21 09:20:13,455 DEBUG bt-mqtt-gw.workers.blescanmulti blescanmulti.py:100:handleDiscovery - Discovered new device: 40:e1:0b:76:54:5a
2020-02-21 09:20:14,184 DEBUG bt-mqtt-gw.workers.blescanmulti blescanmulti.py:100:handleDiscovery - Discovered new device: 2c:d1:f3:c0:d9:60
2020-02-21 09:20:14,539 DEBUG bt-mqtt-gw.workers.blescanmulti blescanmulti.py:100:handleDiscovery - Discovered new device: 04:4b:ed:a7:e1:e8
2020-02-21 09:20:22,899 ERROR bt-mqtt-gw logger.py:50:log_exception - Fatal error while executing worker command: TypeError
Traceback (most recent call last):
  File "./gateway.py", line 89, in <module>
    mqtt.publish(_WORKERS_QUEUE.get(timeout=10).execute())
  File "/home/pi/bt-mqtt-gateway/workers_manager.py", line 58, in execute
    messages = self._callback(*self._args)
  File "/home/pi/bt-mqtt-gateway/workers/blescanmulti.py", line 127, in status_update
    ret += status.generate_messages(device)
  File "/home/pi/bt-mqtt-gateway/workers/blescanmulti.py", line 57, in generate_messages
    if not self.message_sent and self.has_time_elapsed():
  File "/home/pi/bt-mqtt-gateway/workers/blescanmulti.py", line 47, in has_time_elapsed
    return elapsed > self._timeout()
TypeError: '>' not supported between instances of 'float' and 'NoneType'
Traceback (most recent call last):
  File "./gateway.py", line 107, in <module>
    raise e
  File "./gateway.py", line 89, in <module>
    mqtt.publish(_WORKERS_QUEUE.get(timeout=10).execute())
  File "/home/pi/bt-mqtt-gateway/workers_manager.py", line 58, in execute
    messages = self._callback(*self._args)
  File "/home/pi/bt-mqtt-gateway/workers/blescanmulti.py", line 127, in status_update
    ret += status.generate_messages(device)
  File "/home/pi/bt-mqtt-gateway/workers/blescanmulti.py", line 57, in generate_messages
    if not self.message_sent and self.has_time_elapsed():
  File "/home/pi/bt-mqtt-gateway/workers/blescanmulti.py", line 47, in has_time_elapsed
    return elapsed > self._timeout()
TypeError: '>' not supported between instances of 'float' and 'NoneType'


As you can see here the device dc:0d:30:00:01:27 is exiting and the fault is produced.

Du you have any idea on how to proceed?

My config is as follwe
mqtt:

  host: x.x.x.x

  port: 1883

  username: xxxxxxx

  password: xxxxxxxx

  #ca_cert: /etc/ssl/certs/ca-certificates.crt # Uncomment to enable MQTT TLS, update path to appropriate location.

  #ca_verify: False              # Verify TLS certificate chain and host, disable for testing with self-signed certificates, default to True         # All messages will have that prefix added, remove if you dont need this.

  client_id: bt-mqtt-gateway

  availability_topic: lwt_topic




manager:

  workers:

    blescanmulti:    

      args:

        devices:

          bmwx5: DC:0D:30:00:01:21
          bmwi3: DC:0D:30:00:01:27

        topic_prefix: blescan

        available_payload: home

        unavailable_payload: away

        available_timeout: 10

        unavailable_timeout: 

        scan_timeout: 10

        scan_passive: true
      update_interval: 10


Best regards
Lidvar

**Comment by lhusoey** [comment]
Found the problem, unavailable_timeout in config was blank. Entered new value and now it works.
