### ISSUE TITLE
Installation and venv error

### ISSUE THREAD

**Issue by DarkAdibou** [zewelor/bt-mqtt-gateway#160]
Hi

I've carefully read and applied all instructions but cannot run the soft, it gives env error.
I'm on a pi zero, buster, with python 3.7 

sudo ./gateway.py
13:44:45 Starting
Could not install packages due to an EnvironmentError: [Errno 2] Aucun fichier ou dossier de ce type: '/tmp/pip-req-tracker-x4mt6xck/8c8ba74bbbd0ae2fdf1b8fe1d2aa070cadf6a54f8adfc2182d432787'

Could not install packages due to an EnvironmentError: [Errno 2] Aucun fichier ou dossier de ce type: '/tmp/pip-req-tracker-x4mt6xck/f1269e602b05817ef71809938511a43dcedeafa6a504af24f791127f'

Could not install packages due to an EnvironmentError: [Errno 2] Aucun fichier ou dossier de ce type: '/tmp/pip-req-tracker-x4mt6xck/8c8ba74bbbd0ae2fdf1b8fe1d2aa070cadf6a54f8adfc2182d432787'

Traceback (most recent call last):
  File "./gateway.py", line 82, in <module>
    manager.register_workers(global_topic_prefix)
  File "/home/pi/bt-mqtt-gateway/workers_manager.py", line 91, in register_workers
    command_timeout, global_topic_prefix, **worker_config["args"]
  File "/home/pi/bt-mqtt-gateway/workers/base.py", line 7, in __init__
    self._setup()
  File "/home/pi/bt-mqtt-gateway/workers/miflora.py", line 26, in _setup
    from miflora.miflora_poller import MiFloraPoller
ModuleNotFoundError: No module named 'miflora'

my config.yaml also seems correct
mqtt:
  host: 192.168.1.9
  port:
  username: mylogin
  password: mypass
  #ca_cert: /etc/ssl/certs/ca-certificates.crt # Uncomment to enable MQTT TLS, update path to appropriate location.
  #ca_verify: False              # Verify TLS certificate chain and host, disable for testing with self-signed certificates, default to True
  topic_prefix: maison         # All messages will have that prefix added, remove if you dont need this.
  client_id: bt-mqtt-gateway
  availability_topic: lwt_topic

manager:
  sensor_config:
    topic: homeassistant
    retain: true
  topic_subscription:
    update_all:
      topic: homeassistant/status
      payload: online
  command_timeout: 35           # Timeout for worker operations. Can be removed if the default of 35 seconds is sufficient.
  workers:
    mysensors:
      command_timeout: 35       # Optional override of globally set command_timeout.
      args:
        port: /dev/ttyACM0
        baudrate: 9600
        topic_prefix: mysensors/out
    miflora:
      args:
        devices:
          ficus: C4:7C:8D:6A:35:32
        topic_prefix: miflora
      update_interval: 600

**Comment by zewelor** [comment]
Try to install git, it should solve this.
