### ISSUE TITLE
Issue running gateway.py

### ISSUE THREAD

**Issue by leopold005** [zewelor/bt-mqtt-gateway#167]
I feel like I'm getting closer!

Now I'm hitting a message when running the line _sudo ./gateway.py_.  This is the output:

```
(.venv) pi@BTGateway:~/bt-mqtt-gateway $ sudo ./gateway.py
Traceback (most recent call last):
  File "./gateway.py", line 11, in <module>
    import logger
  File "/home/pi/bt-mqtt-gateway/logger.py", line 3, in <module>
    import yaml
ModuleNotFoundError: No module named 'yaml'
```
It's that last line that bothers me.  Anyone got any ideas if this is normal or something I need to concern myself with?  And if it's the latter, what's the fix?

Sorry again, complete Linux noob just trying to get bluetooth stuff working!

**Comment by Yvon-Indel** [comment]
Hi,
Maybe the yaml module is not installed.
Did you try to install it ?
`pip3 install pyyaml`

**Comment by leopold005** [comment]
I tried that, it said the requirement is already satisfied, and still no joy, same error.

**Comment by Tualua** [comment]
Got the same error on fresh installation

**Comment by Tualua** [comment]
Seems like the root of the problem is running gateway.py with sudo. If you need to run it with sudo you need to execute all pip3 install ... with sudo.

But as I understand this is not good way because every python tutorial says 'never run pip install with sudo'

To dev: is there any way to fix this?

**Comment by Bottesford** [comment]
I have the same problem. Seems we must run with sudo or I get: 
bluepy.btle.BTLEManagementError: Failed to execute management command 'le on' (code: 20, error: Permission Denied)

Do I really need to install everything as sudo? That doesn't seem right to me having set it up in a venv.

**Comment by thallaa** [comment]
I ran into this very same problem. I ended up removing all of the VENV-parts from the service.sh and then it runs fine. So my service.sh looks like this:
```
#!/bin/sh
set -e
SCRIPT_DIR=$( cd "$( dirname "$0" )" >/dev/null 2>&1 && pwd )
cd "$SCRIPT_DIR"
python3 ./gateway.py "$@"
```
Perhaps someone handy with venv could point out how to do this with it but I'm happy with this now.
