### ISSUE TITLE
Error during gateway start (Errno 2)

### ISSUE THREAD

**Issue by uli6** [zewelor/bt-mqtt-gateway#190]
[x] I've read the [Troubleshooting Wiki](https://github.com/zewelor/bt-mqtt-gateway/wiki/Troubleshooting), my problem is not described there and I am  already using the specified minimum bluez version.

**Describe the bug**

The script is not starting.

**To Reproduce**
```

(.venv) pi@raspberrypi:~/bt-mqtt-gateway $ sudo ./gateway.py
16:43:33 Starting
Could not install packages due to an EnvironmentError: [Errno 2] No such file or directory: '/tmp/pip-req-tracker-uexxzddf/842a9cdb9c2fec1838b90e5a1c92a091b46562f90b8268bda8196a1d'

Could not install packages due to an EnvironmentError: [Errno 2] No such file or directory: '/tmp/pip-req-tracker-uexxzddf/f1269e602b05817ef71809938511a43dcedeafa6a504af24f791127f'

Could not install packages due to an EnvironmentError: [Errno 2] No such file or directory: '/tmp/pip-req-tracker-uexxzddf/842a9cdb9c2fec1838b90e5a1c92a091b46562f90b8268bda8196a1d'

Traceback (most recent call last):
  File "./gateway.py", line 81, in <module>
    manager.register_workers(global_topic_prefix)
  File "/home/pi/bt-mqtt-gateway/workers_manager.py", line 92, in register_workers
    command_timeout, global_topic_prefix, **worker_config["args"]
  File "/home/pi/bt-mqtt-gateway/workers/base.py", line 9, in __init__
    self._setup()
  File "/home/pi/bt-mqtt-gateway/workers/miflora.py", line 28, in _setup
    from miflora.miflora_poller import MiFloraPoller
ModuleNotFoundError: No module named 'miflora'
```

**Expected behavior**

**Config**
Used config

**Debug gateway logs**
```
(.venv) pi@raspberrypi:~/bt-mqtt-gateway $ sudo ./gateway.py -d
2020-07-15 16:49:21,995 INFO bt-mqtt-gw gateway.py:75:<module> - Starting
Traceback (most recent call last):
  File "./gateway.py", line 77, in <module>
    global_topic_prefix = settings["mqtt"].get("topic_prefix")
KeyError: 'mqtt
```

**Server (please complete the following information):**
 - OS: [Linux]
 - Distro: [Raspbian]

**Additional context**

**Comment by iso** [comment]
In case you're still stuck: adding miflora module should fix the  issue:
```
source .venv/bin/activate
sudo pip3 install miflora
```
