### ISSUE TITLE
lywsd03mmc  object has no attribute 'passive'

### ISSUE THREAD

**Issue by pidzej** [zewelor/bt-mqtt-gateway#204]
**Describe the bug**
When added 2 lywsd03mmc getting error when start deamon
lywsd03mmc running custom firmware and advertising type set to custom 
**Config**
```
manager:
  sensor_config:
    topic: homeassistant
    retain: true
  topic_subscription:
    update_all:
      topic: homeassistant/status
      payload: online
  command_timeout: 120
  workers:
    lywsd03mmc:
      args:
        devices:
          657: A4:C1:38:04:E6:57
          54E: A4:C1:38:A2:D5:4E
        topic_prefix: mijasensor_gen2
      update_interval: 240
      passive: false
```

**Debug gateway logs**
run gateway.py with -d switch and paste formatted output log
```
2021-01-05 00:22:32,446 DEBUG bt-mqtt-gw.workers_manager workers_manager.py:83:register_workers - Added thermostat config with a 2 seconds timeout
2021-01-05 00:22:32,451 DEBUG bt-mqtt-gw.workers_manager workers_manager.py:93:register_workers - Added thermostat worker with 240 seconds interval and a 120 seconds timeout
2021-01-05 00:22:33,551 INFO bt-mqtt-gw.workers.lywsd03mmc lywsd03mmc.py:15:_setup - Adding 2 lywsd03mmc devices
2021-01-05 00:22:33,553 INFO bt-mqtt-gw.workers.lywsd03mmc lywsd03mmc.py:18:_setup - Adding lywsd03mmc device '657' (A4:C1:38:04:E6:57)
Traceback (most recent call last):
  File "./gateway.py", line 83, in <module>
    manager.register_workers(global_topic_prefix)
  File "/home/pi/bt-mqtt-gateway/workers_manager.py", line 78, in register_workers
    command_timeout, global_topic_prefix, **worker_config["args"]
  File "/home/pi/bt-mqtt-gateway/workers/base.py", line 9, in __init__
    self._setup()
  File "/home/pi/bt-mqtt-gateway/workers/lywsd03mmc.py", line 19, in _setup
    self.devices[name] = lywsd03mmc(mac, timeout=self.command_timeout, passive=self.passive)
AttributeError: 'Lywsd03MmcWorker' object has no attribute 'passive'

```

**Server (please complete the following information):**
 - Distro: Raspbian

**Comment by pidzej** [comment]
sorry duplicated
