### ISSUE TITLE
No module named 'pip._internal' on startup

### ISSUE THREAD

**Issue by snizzleorg** [zewelor/bt-mqtt-gateway#22]
running on raspbian jessie, python 3.4

```
Traceback (most recent call last):
  File "gateway.py", line 15, in <module>
    from workers_manager import WorkersManager
  File "/home/pi/bt-mqtt-gateway/workers_manager.py", line 4, in <module>
    from pip._internal import main as pip_main
ImportError: No module named 'pip._internal'
```

**Comment by snizzleorg** [comment]
Seems as ```pip3  install -U pip```helped with the above but now I'm getting this:
```
Starting
Traceback (most recent call last):
  File "./gateway.py", line 30, in <module>
    manager.register_workers(settings['manager']).start(mqtt)
  File "/home/pi/bt-mqtt-gateway/workers_manager.py", line 34, in register_workers
    module_obj = importlib.import_module("workers.%s" % worker_name)
  File "/usr/lib/python3.4/importlib/__init__.py", line 109, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "<frozen importlib._bootstrap>", line 1471, in exec_module
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "/home/pi/bt-mqtt-gateway/workers/thermostat.py", line 5, in <module>
    from workers.base import BaseWorker
  File "/home/pi/bt-mqtt-gateway/workers/base.py", line 11
    return '/'.join([self.topic_prefix, *args])
                                           ^
SyntaxError: can use starred expression only as assignment target
```

**Comment by zewelor** [comment]
Hi

from what I've googled, that syntax is supported from python 3.5. I've wrote it with python 3.6, so not sure what more can not work on older versions. Try newer python, it should work then.

**Comment by snizzleorg** [comment]
@zewelor thanks. I'll try that. Installing python 3.7 as we speak. however on my rpi 1 this will probably take a few days... will report back

**Comment by snizzleorg** [comment]
@zewelor a few days later I got pyth3.6 installed and all the dependencies. and the gateway runs.

Thanks!

**Comment by zewelor** [comment]
Great to hear that ! I've added python >= 3.5 to readme to avoid future confusion
