### ISSUE TITLE
MiScale 2 time out error

### ISSUE THREAD

**Issue by nightcat91** [zewelor/bt-mqtt-gateway#73]
Hi,

is the Xiaomi miscale 2 supported (the version with body fat measurements)??

I have one of them here and I only get the following error when starting the gateway in debug mode:

```
pi@raspberrypi:~/bt-mqtt-gateway $ sudo ./gateway.py -d
2019-06-02 23:15:01,611 INFO bt-mqtt-gw gateway.py:39:<module> - Starting
2019-06-02 23:15:01,618 DEBUG bt-mqtt-gw.mqtt mqtt.py:21:__init__ - Setting LWT to: bt2mqtt/LWT
2019-06-02 23:15:02,087 DEBUG bt-mqtt-gw.workers_manager workers_manager.py:59:register_workers - Added miscale worker with 150 seconds interval and a 35 seconds timeout
2019-06-02 23:15:03,640 DEBUG bt-mqtt-gw.mqtt mqtt.py:76:callbacks_subscription - Subscribing to: bt2mqtt/miscale/update_interval
2019-06-02 23:15:03,646 DEBUG bt-mqtt-gw.mqtt mqtt.py:76:callbacks_subscription - Subscribing to: bt2mqtt/homeassistant/status
2019-06-02 23:15:03,671 DEBUG bt-mqtt-gw.workers_manager workers_manager.py:106:update_all - Updating all workers
2019-06-02 23:15:14,081 ERROR bt-mqtt-gw logger.py:48:log_exception - Retrieving the weight from miscale device C8:A1:20:20:91:43 timed out after 5 seconds
Traceback (most recent call last):
  File "./gateway.py", line 49, in <module>
    mqtt.publish(_WORKERS_QUEUE.get(timeout=10).execute())
  File "/home/pi/bt-mqtt-gateway/workers_manager.py", line 34, in execute
    messages = self._callback(*self._args)
  File "/home/pi/bt-mqtt-gateway/workers/miscale.py", line 18, in status_update
    return [MqttMessage(topic=self.format_topic('weight/kg'), payload=self._get_weight())]
  File "/home/pi/bt-mqtt-gateway/workers/miscale.py", line 29, in _get_weight
    time.sleep(1)
  File "/usr/local/lib/python3.5/dist-packages/interruptingcow/__init__.py", line 74, in handler
    raise exception
TimeoutError: Retrieving the weight from miscale device C8:A1:20:20:91:43 timed out after 5 seconds
2019-06-02 23:17:43,702 ERROR bt-mqtt-gw logger.py:48:log_exception - Retrieving the weight from miscale device C8:A1:20:20:91:43 timed out after 5 seconds
Traceback (most recent call last):
  File "./gateway.py", line 49, in <module>
    mqtt.publish(_WORKERS_QUEUE.get(timeout=10).execute())
  File "/home/pi/bt-mqtt-gateway/workers_manager.py", line 34, in execute
    messages = self._callback(*self._args)
  File "/home/pi/bt-mqtt-gateway/workers/miscale.py", line 18, in status_update
    return [MqttMessage(topic=self.format_topic('weight/kg'), payload=self._get_weight())]
  File "/home/pi/bt-mqtt-gateway/workers/miscale.py", line 29, in _get_weight
    time.sleep(1)
  File "/usr/local/lib/python3.5/dist-packages/interruptingcow/__init__.py", line 74, in handler
    raise exception
TimeoutError: Retrieving the weight from miscale device C8:A1:20:20:91:43 timed out after 5 seconds
2019-06-02 23:20:13,718 ERROR bt-mqtt-gw logger.py:48:log_exception - Retrieving the weight from miscale device C8:A1:20:20:91:43 timed out after 5 seconds
Traceback (most recent call last):
  File "./gateway.py", line 49, in <module>
    mqtt.publish(_WORKERS_QUEUE.get(timeout=10).execute())
  File "/home/pi/bt-mqtt-gateway/workers_manager.py", line 34, in execute
    messages = self._callback(*self._args)
  File "/home/pi/bt-mqtt-gateway/workers/miscale.py", line 18, in status_update
    return [MqttMessage(topic=self.format_topic('weight/kg'), payload=self._get_weight())]
  File "/home/pi/bt-mqtt-gateway/workers/miscale.py", line 29, in _get_weight
    time.sleep(1)
  File "/usr/local/lib/python3.5/dist-packages/interruptingcow/__init__.py", line 74, in handler
    raise exception
TimeoutError: Retrieving the weight from miscale device C8:A1:20:20:91:43 timed out after 5 seconds
```

The connection to the mqtt host work, I get the LWT message.

The mac adress of the scale is correctly set up in the worker, i double checked.

The scale has never been connected to a MiFit App on any phone, if that makes a difference.

Running on a raspberry pi zero w
Linux raspberrypi 4.14.79+ #1159 Sun Nov 4 17:28:08 GMT 2018 armv6l GNU/Linux

**Comment by zewelor** [comment]
I don't have V2 so not sure. Never heard of anyone reported that V2 works with this code. So probably not ?

**Comment by nightcat91** [comment]
I would like to try and get it to work, maybe that would help others as well.

Just not sure how exactly I would start with that???
I did have a look into the worker file of the xiaomi scale and saw that you are looking for a specific value and then do some math with that.

Would you be able to help me with this? Maybe I can find out the bluetooth messages from the scale and maybe you could do the code for it, since I am not good at programing?

Is there a good program or app to capture all the bluetooth content that the scale is sending so I could give that content to you?

Thanks a lot

**Comment by zewelor** [comment]
Hi

I think there is good chance that someone already reversed v2 and protocol is described somewhere. Here is good explaination of reverse process for V1, you can try to recreate that. https://github.com/oliexdev/openScale/wiki/Xiaomi-Bluetooth-Mi-Scale

Code in miscale worker is just copied from some exmplaes, available on the internet. You can take this worker and play with it to get correct weight retrieving procedure for V2.

**Comment by bbbenji** [comment]
This repository has been updated with support for the v2 scale. Please update and let us know how it works for you. Closing for now.

**Comment by nightcat91** [comment]
Hi,

@bbbenji , thanks for letting me know about the update.
I just tested it (complete new install) and I seem to have a few issues...

I used the example config and only put in my mqtt server ip, username and password.
Then I deletet all workers except the miscale one and put in my scales mac adress and left all the other settings default for now.

When I start the gateway.py -d I get the following output:


And on my Mqtt broker I can see that the gateway does a pretty fast and infinite loop making a new connection to the broker... about once per second:
This is the log of my broker, its the "MQTT Server & Web client" from the "Community Hass.io Add-ons": https://github.com/hassio-addons/addon-mqtt/blob/master/README.md
```
1578833259: New client connected from 10.11.11.2 as bt-mqtt-gateway (p2, c0, k60, u'bt2mqtt').
1578833260: New connection from 10.11.11.2 on port 1883.
1578833260: Client bt-mqtt-gateway already connected, closing old connection.
1578833260: New client connected from 10.11.11.2 as bt-mqtt-gateway (p2, c0, k60, u'bt2mqtt').
1578833262: New connection from 10.11.11.2 on port 1883.
1578833262: Client bt-mqtt-gateway already connected, closing old connection.
1578833262: New client connected from 10.11.11.2 as bt-mqtt-gateway (p2, c0, k60, u'bt2mqtt').
1578833263: New connection from 10.11.11.2 on port 1883.
1578833263: Client bt-mqtt-gateway already connected, closing old connection.
1578833263: New client connected from 10.11.11.2 as bt-mqtt-gateway (p2, c0, k60, u'bt2mqtt').
1578833264: New connection from 10.11.11.2 on port 1883.
1578833264: Client bt-mqtt-gateway already connected, closing old connection.
1578833264: New client connected from 10.11.11.2 as bt-mqtt-gateway (p2, c0, k60, u'bt2mqtt').
1578833265: New connection from 10.11.11.2 on port 1883.
1578833265: Client bt-mqtt-gateway already connected, closing old connection.
```

Also there are lots and lots of LWT messages, about 1x online and 1x offline on two different topics per second. (its kind of spamming my mqtt broker).
Sadly the mqtt message that the gateway apparently send (see log above) never gets to the mqtt broker.
