### ISSUE TITLE
Bluepy missing from requirements

### ISSUE THREAD

**Issue by bistory** [zewelor/bt-mqtt-gateway#77]
**Describe the bug**
I installed bt-mqtt-gateway on a freshly installed Raspbian (latest release). When trying to launch the daemon, it complains about bluepy missing...
Installing it using `sudo pip3 install bluepy`works :-)

**Error**

```
pi@raspberrypi:~/bt-mqtt-gateway $ sudo ./gateway.py -d
2019-06-26 19:38:04,114 INFO bt-mqtt-gw gateway.py:39:<module> - Starting
2019-06-26 19:38:04,120 DEBUG bt-mqtt-gw.mqtt mqtt.py:23:__init__ - Setting LWT to: router/lwt_topic
2019-06-26 19:38:12,025 INFO bt-mqtt-gw.workers.mithermometer mithermometer.py:18:_setup - Adding 1 mithermometer devices
2019-06-26 19:38:12,028 DEBUG bt-mqtt-gw.workers.mithermometer mithermometer.py:20:_setup - Adding mithermometer device 'living_room' (58:2D:34:10:40:D0)
2019-06-26 19:38:12,038 ERROR btlewrap.bluepy bluepy.py:101:check_backend - bluepy not found: No module named 'bluepy'
2019-06-26 19:38:12,043 DEBUG bt-mqtt-gw.workers_manager workers_manager.py:60:register_workers - Added mithermometer config with a 2 seconds timeout
2019-06-26 19:38:12,045 DEBUG bt-mqtt-gw.workers_manager workers_manager.py:65:register_workers - Added mithermometer worker with 300 seconds interval and a 35 seconds timeout
2019-06-26 19:38:12,075 DEBUG bt-mqtt-gw.mqtt mqtt.py:77:callbacks_subscription - Subscribing to: router/mithermometer/update_interval
2019-06-26 19:38:12,080 DEBUG bt-mqtt-gw.mqtt mqtt.py:77:callbacks_subscription - Subscribing to: router/homeassistant/status
2019-06-26 19:38:12,090 DEBUG bt-mqtt-gw.workers_manager workers_manager.py:36:execute - Execution result of command MithermometerWorker.config: [{'topic': 'sensor/mithermometer_living_room_temperature/config', 'payload': '{"unique_id": "bt-mqtt-gateway_mithermometer_living_room_temperature", "state_topic": "mithermometer/living_room/temperature", "device_class": "temperature", "device": {"identifiers": ["58:2D:34:10:40:D0", "bt-mqtt-gateway_mithermometer_living_room"], "manufacturer": "Xiaomi", "model": "LYWSD(CGQ/01ZM)", "name": "Mithermometer Living_Room"}, "name": "mithermometer_living_room_temperature"}'}, {'topic': 'sensor/mithermometer_living_room_humidity/config', 'payload': '{"unique_id": "bt-mqtt-gateway_mithermometer_living_room_humidity", "state_topic": "mithermometer/living_room/humidity", "device_class": "humidity", "device": {"identifiers": ["58:2D:34:10:40:D0", "bt-mqtt-gateway_mithermometer_living_room"], "manufacturer": "Xiaomi", "model": "LYWSD(CGQ/01ZM)", "name": "Mithermometer Living_Room"}, "name": "mithermometer_living_room_humidity"}'}, {'topic': 'sensor/mithermometer_living_room_battery/config', 'payload': '{"unique_id": "bt-mqtt-gateway_mithermometer_living_room_battery", "state_topic": "mithermometer/living_room/battery", "device_class": "battery", "device": {"identifiers": ["58:2D:34:10:40:D0", "bt-mqtt-gateway_mithermometer_living_room"], "manufacturer": "Xiaomi", "model": "LYWSD(CGQ/01ZM)", "name": "Mithermometer Living_Room"}, "name": "mithermometer_living_room_battery"}'}]
2019-06-26 19:38:12,117 DEBUG bt-mqtt-gw.workers_manager workers_manager.py:116:update_all - Updating all workers
2019-06-26 19:38:12,120 INFO bt-mqtt-gw.workers.mithermometer mithermometer.py:39:status_update - Updating 1 mithermometer devices
2019-06-26 19:38:12,122 DEBUG bt-mqtt-gw.workers.mithermometer mithermometer.py:42:status_update - Updating mithermometer device 'living_room' (58:2D:34:10:40:D0)
2019-06-26 19:38:12,132 ERROR bt-mqtt-gw logger.py:48:log_exception - Fatal error while executing worker command: ModuleNotFoundError
Traceback (most recent call last):
  File "./gateway.py", line 49, in <module>
    mqtt.publish(_WORKERS_QUEUE.get(timeout=10).execute())
  File "/home/pi/bt-mqtt-gateway/workers_manager.py", line 34, in execute
    messages = self._callback(*self._args)
  File "/home/pi/bt-mqtt-gateway/workers/mithermometer.py", line 45, in status_update
    ret += self.update_device_state(name, data["poller"])
  File "/home/pi/bt-mqtt-gateway/workers/mithermometer.py", line 54, in update_device_state
    ret.append(MqttMessage(topic=self.format_topic(name, attr), payload=poller.parameter_value(attr)))
  File "/usr/local/lib/python3.7/dist-packages/mithermometer/mithermometer_poller.py", line 136, in parameter_value
    self.fill_cache()
  File "/usr/local/lib/python3.7/dist-packages/mithermometer/mithermometer_poller.py", line 60, in fill_cache
    self.firmware_version()
  File "/usr/local/lib/python3.7/dist-packages/mithermometer/mithermometer_poller.py", line 109, in firmware_version
    with self._bt_interface.connect(self._mac) as connection:
  File "/usr/local/lib/python3.7/dist-packages/btlewrap/base.py", line 44, in __enter__
    self._backend.connect(self._mac)
  File "/usr/local/lib/python3.7/dist-packages/btlewrap/bluepy.py", line 48, in connect
    from bluepy.btle import Peripheral
ModuleNotFoundError: No module named 'bluepy'
Traceback (most recent call last):
  File "./gateway.py", line 59, in <module>
    raise e
  File "./gateway.py", line 49, in <module>
    mqtt.publish(_WORKERS_QUEUE.get(timeout=10).execute())
  File "/home/pi/bt-mqtt-gateway/workers_manager.py", line 34, in execute
    messages = self._callback(*self._args)
  File "/home/pi/bt-mqtt-gateway/workers/mithermometer.py", line 45, in status_update
    ret += self.update_device_state(name, data["poller"])
  File "/home/pi/bt-mqtt-gateway/workers/mithermometer.py", line 54, in update_device_state
    ret.append(MqttMessage(topic=self.format_topic(name, attr), payload=poller.parameter_value(attr)))
  File "/usr/local/lib/python3.7/dist-packages/mithermometer/mithermometer_poller.py", line 136, in parameter_value
    self.fill_cache()
  File "/usr/local/lib/python3.7/dist-packages/mithermometer/mithermometer_poller.py", line 60, in fill_cache
    self.firmware_version()
  File "/usr/local/lib/python3.7/dist-packages/mithermometer/mithermometer_poller.py", line 109, in firmware_version
    with self._bt_interface.connect(self._mac) as connection:
  File "/usr/local/lib/python3.7/dist-packages/btlewrap/base.py", line 44, in __enter__
    self._backend.connect(self._mac)
  File "/usr/local/lib/python3.7/dist-packages/btlewrap/bluepy.py", line 48, in connect
    from bluepy.btle import Peripheral
ModuleNotFoundError: No module named 'bluepy'
```

**Server (please complete the following information):**
 - OS: [Linux]
 - Distro: [Raspbian]
 - Version [June 2019]

**Comment by zewelor** [comment]
Added bluepy to requirements, thanks ( https://github.com/zewelor/bt-mqtt-gateway/commit/8dfda3080dd1b53c0f7c45bf7637ddc79a2c6287 )
