### ISSUE TITLE
Support for Xiaomi Mijia temperature and humidity sensor

### ISSUE THREAD

**Issue by kobush** [zewelor/bt-mqtt-gateway#94]
Please add support for the Xiaomi Mijia temperature & humidity sensor. It's a nice lowcost BLE device with LCD display https://esphome.io/components/sensor/xiaomi_mijia.html 

Here is a python library that supports it:
https://github.com/ratcashdev/mitemp
https://zsiti.eu/xiaomi-mijia-hygrothermo-v2-sensor-data-on-raspberry-pi/

**Comment by Maczuga** [comment]
It is supported, listed as "Xiaomi Aqara thermometer via mi thermometer". Somebody just mistitled the device in readme file, as there is no Aqara temperature / humidity bluetooth sensor.

I have 5 of them running using this library.

**Comment by kobush** [comment]
I'm not sure if we are talking about the same device model here. Mine are round devices with LCD display. I have tried to configure this but it couldn't connect. Using hctool lescan devices are listed as MJ_HT_V1:

```
pi@raspi-zero:~/bt-mqtt-gateway $ sudo hcitool lescan
LE Scan ...
58:0D:27:4B:C5:20 (unknown)
01:0D:B2:C9:6F:BD (unknown)
58:2D:34:32:63:38 (unknown)
58:2D:34:32:63:38 MJ_HT_V1
C4:7C:8D:6B:27:9F (unknown)
C4:7C:8D:6B:27:9F Flower care
58:0D:27:4B:C5:20 (unknown)
C4:7C:8D:6B:23:D3 (unknown)
C4:7C:8D:6B:18:DC (unknown)
58:2D:34:32:5B:42 (unknown)
58:2D:34:32:63:58 (unknown)
C4:7C:8D:6B:23:D3 Flower care
C4:7C:8D:6B:18:DC Flower care
C8:0F:10:A5:09:CF (unknown)
58:2D:34:32:5B:42 MJ_HT_V1
58:2D:34:32:63:58 MJ_HT_V1
58:2D:34:32:5A:AB (unknown)
58:2D:34:32:5A:AB MJ_HT_V1
C8:0F:10:A5:09:CF MI_SCALE
```
I configured just one of them and got DeviceTimeutError:
```
2019-09-03 10:57:32,891 INFO bt-mqtt-gw.workers.mithermometer mithermometer.py:60:status_update - Updating 1 mithermometer devices
2019-09-03 10:57:32,894 DEBUG bt-mqtt-gw.workers.mithermometer mithermometer.py:63:status_update - Updating mithermometer device 'library' (58:2D:34:32:63:58)
2019-09-03 10:57:38,902 ERROR bt-mqtt-gw.workers.mithermometer logger.py:48:log_exception - Time out during update of mithermometer device 'library' (58:2D:34:32:63:58)
Traceback (most recent call last):
  File "/home/pi/bt-mqtt-gateway/workers/mithermometer.py", line 66, in status_update
    yield self.update_device_state(name, data["poller"])
  File "/home/pi/bt-mqtt-gateway/.venv/lib/python3.5/site-packages/interruptingcow/__init__.py", line 153, in inner
    return func(*args, **kwargs)
  File "/home/pi/bt-mqtt-gateway/workers/mithermometer.py", line 77, in update_device_state
    ret.append(MqttMessage(topic=self.format_topic(name, attr), payload=poller.parameter_value(attr)))
  File "/home/pi/bt-mqtt-gateway/.venv/lib/python3.5/site-packages/mithermometer/mithermometer_poller.py", line 136, in parameter_value
    self.fill_cache()
  File "/home/pi/bt-mqtt-gateway/.venv/lib/python3.5/site-packages/mithermometer/mithermometer_poller.py", line 60, in fill_cache
    self.firmware_version()
  File "/home/pi/bt-mqtt-gateway/.venv/lib/python3.5/site-packages/mithermometer/mithermometer_poller.py", line 109, in firmware_version
    with self._bt_interface.connect(self._mac) as connection:
  File "/home/pi/bt-mqtt-gateway/.venv/lib/python3.5/site-packages/btlewrap/base.py", line 44, in __enter__
    self._backend.connect(self._mac)
  File "/home/pi/bt-mqtt-gateway/.venv/lib/python3.5/site-packages/btlewrap/bluepy.py", line 26, in _func_wrapper
    return func(*args, **kwargs)
  File "/home/pi/bt-mqtt-gateway/.venv/lib/python3.5/site-packages/btlewrap/bluepy.py", line 55, in connect
    self._peripheral = Peripheral(mac, iface=iface)
  File "/home/pi/bt-mqtt-gateway/.venv/lib/python3.5/site-packages/bluepy/btle.py", line 391, in __init__
    self._connect(deviceAddr, addrType, iface)
  File "/home/pi/bt-mqtt-gateway/.venv/lib/python3.5/site-packages/bluepy/btle.py", line 436, in _connect
    rsp = self._getResp('stat')
  File "/home/pi/bt-mqtt-gateway/.venv/lib/python3.5/site-packages/bluepy/btle.py", line 407, in _getResp
    resp = self._waitResp(wantType + ['ntfy', 'ind'], timeout)
  File "/home/pi/bt-mqtt-gateway/.venv/lib/python3.5/site-packages/bluepy/btle.py", line 347, in _waitResp
    rv = self._helper.stdout.readline()
  File "/home/pi/bt-mqtt-gateway/.venv/lib/python3.5/site-packages/interruptingcow/__init__.py", line 74, in handler
    raise exception
exceptions.DeviceTimeoutError
2019-09-03 10:57:38,967 DEBUG bt-mqtt-gw.workers_manager workers_manager.py:48:execute - Execution result of command MithermometerWorker.status_update: []
```

**Comment by wutu** [comment]
After increasing the timeout, data can be retrieved.
`per_device_timeout: 20`
